### ISSUE TITLE
Any plan to support list/retrieve/download live_video?

### ISSUE THREAD

**Issue by tigren** [onfido/api-python-client#4]
I noticed that Onfido has REST apis for live_videos: https://documentation.onfido.com/?python#live-videos  , while this Python sdk doesn't have related apis.

Do you have any plan to support live_video in Python sdk? Before that I guess I have to call the REST api directly.

Appreciate for your answer.

**Comment by ciaran16** [comment]
This is now supported in v1.6.0, and then 2.1.0 onwards
